# Generated by Django 4.2.6 on 2023-10-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
